# Generated by Django 5.2.8 on 2025-12-01 20:13

import MushroomWiki.main_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroom',
            name='image_url',
        ),
        migrations.AddField(
            model_name='mushroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mushrooms/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[MushroomWiki.main_app.validators.only_letters_spaces]),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2), MushroomWiki.main_app.validators.only_letters_spaces]),
        ),
    ]
